
lights = [
        ( "Bijkeuken", 2 ),
        ( "Keuken", 4 ),
        ( "Wand eetplaats 1", 6 ),
        ( "Wand eetplaats 2", 8 ),
        ( "Plafond eetplaats 1", 10 ),
        ( "Plafond eetplaats 2", 12 ),
        ( "Inkomhal 1", 14 ),
        ( "Inkomhal 2", 16 ),
        ( "Inkomhal 3", 18 ),
        ( "Vestiaire", 20 ),
        ( "Zithoek", 22 ),
        ( "Douche gelijkvoers", 24 ),
        ( "WC gelijkvloers", 26 ),
        ( "Berging", 28 ),
        ( "Overloop 1ste", 30 ),
        ( "Inrit", 32 ),
        ( "WC 1ste", 34 ),
        ( "Werkblad keuken", 36 ),
        ( "Slaapkamer 1", 38 ),
        ( "Slaapkamer 2", 40 ),
        ( "Wachthal 1ste", 42 ),
        ( "CV lokaal", 44 ),
        ( "Slaapkamer 3", 46 ),
        ( "Dressing", 48 ),
        ( "Achterdeur keuken", 50 ),
        ( "Terras gelijkvloers", 52 ),
        ( "Dakterras", 54 ),
        ( "Overloop 2de", 56 ),
        ( "Plafond badkamer 1ste", 58 ),
        ( "Lavabo badkamer 1ste", 60 ),
        ( "Badkamer 2de", 62 ),
        ]
